fix: modal tailwindcss config
nextui-org/nextui-cli pull request #97
Opened 2024-08-27 14:26 UTC by winchesHe

## 📝 Description

## ✅ Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

2024-08-28 05:08 UTC, winchesHe commented
fixed in the file `src/constants/required.ts`

2024-08-28 10:57 UTC, wingkwong requested changes

2024-08-28 10:57 UTC, wingkwong commented on src/helpers/debug.ts
> +  if (getStoreSync('debug')) {
```ts
if (!components.length || !getStoreSync('debug')) return
```

2024-08-28 10:57 UTC, wingkwong commented on src/helpers/debug.ts
> +  if (getStoreSync('debug')) {
```ts
if (!components.length || !getStoreSync('debug')) return
```

2024-08-28 10:57 UTC, wingkwong commented on src/actions/add-action.ts
> +    // Temporary add the components to the package.json file
grammar: 

```
Temporarily add the components to the package.json file
```

2024-08-28 10:57 UTC, wingkwong commented on src/actions/add-action.ts
> +    // Remove the temporary added components from the package.json file
grammar: 

```
Remove the temporarily added components from the package.json file
```

2024-09-17 17:35 UTC, wingkwong reviewed
please check `src/actions/upgrade-action.ts` L41.

2024-09-18 17:07 UTC, wingkwong approved these changes

2024-09-19 01:03 UTC, merged